import type { SettingsSection } from "renderer/stores/settings-state";

export const SETTING_ITEM_ID = {
	ACCOUNT_PROFILE: "account-profile",
	ACCOUNT_SIGNOUT: "account-signout",

	ORGANIZATION_LOGO: "organization-logo",
	ORGANIZATION_NAME: "organization-name",
	ORGANIZATION_SLUG: "organization-slug",
	ORGANIZATION_MEMBERS_LIST: "organization-members-list",
	ORGANIZATION_MEMBERS_INVITE: "organization-members-invite",
	ORGANIZATION_MEMBERS_PENDING_INVITATIONS:
		"organization-members-pending-invitations",

	APPEARANCE_THEME: "appearance-theme",
	APPEARANCE_MARKDOWN: "appearance-markdown",
	APPEARANCE_CUSTOM_THEMES: "appearance-custom-themes",

	RINGTONES_NOTIFICATION: "ringtones-notification",

	KEYBOARD_SHORTCUTS: "keyboard-shortcuts",

	BEHAVIOR_CONFIRM_QUIT: "behavior-confirm-quit",
	BEHAVIOR_BRANCH_PREFIX: "behavior-branch-prefix",

	TERMINAL_PRESETS: "terminal-presets",
	TERMINAL_QUICK_ADD: "terminal-quick-add",
	TERMINAL_AUTO_APPLY_PRESET: "terminal-auto-apply-preset",
	TERMINAL_PERSISTENCE: "terminal-persistence",
	TERMINAL_SESSIONS: "terminal-sessions",
	TERMINAL_LINK_BEHAVIOR: "terminal-link-behavior",

	INTEGRATIONS_LINEAR: "integrations-linear",
	INTEGRATIONS_GITHUB: "integrations-github",

	BILLING_OVERVIEW: "billing-overview",
	BILLING_PLANS: "billing-plans",
	BILLING_USAGE: "billing-usage",

	PROJECT_NAME: "project-name",
	PROJECT_PATH: "project-path",
	PROJECT_SCRIPTS: "project-scripts",
	PROJECT_BRANCH_PREFIX: "project-branch-prefix",

	WORKSPACE_NAME: "workspace-name",
	WORKSPACE_BRANCH: "workspace-branch",
	WORKSPACE_PATH: "workspace-path",

	// API Keys
	API_KEYS_LIST: "api-keys-list",
	API_KEYS_GENERATE: "api-keys-generate",
} as const;

export type SettingItemId =
	(typeof SETTING_ITEM_ID)[keyof typeof SETTING_ITEM_ID];

export interface SettingsItem {
	id: SettingItemId;
	section: SettingsSection;
	title: string;
	description: string;
	keywords: string[];
}

export const SETTINGS_ITEMS: SettingsItem[] = [
	{
		id: SETTING_ITEM_ID.ACCOUNT_PROFILE,
		section: "account",
		title: "Profile",
		description: "Your profile information",
		keywords: [
			"account",
			"name",
			"email",
			"avatar",
			"user",
			"profile",
			"picture",
			"photo",
			"me",
		],
	},
	{
		id: SETTING_ITEM_ID.ACCOUNT_SIGNOUT,
		section: "account",
		title: "Sign Out",
		description: "Sign out of your account",
		keywords: [
			"account",
			"sign out",
			"logout",
			"log out",
			"disconnect",
			"leave",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_LOGO,
		section: "organization",
		title: "Organization Logo",
		description: "Upload and manage your organization's logo",
		keywords: [
			"organization",
			"logo",
			"image",
			"branding",
			"upload",
			"icon",
			"picture",
			"avatar",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_NAME,
		section: "organization",
		title: "Organization Name",
		description: "Change your organization's display name",
		keywords: [
			"organization",
			"name",
			"rename",
			"title",
			"company",
			"team name",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_SLUG,
		section: "organization",
		title: "Organization Slug",
		description: "Your organization's unique identifier",
		keywords: [
			"organization",
			"slug",
			"url",
			"identifier",
			"subdomain",
			"link",
			"unique",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_MEMBERS_LIST,
		section: "organization",
		title: "Team Members",
		description: "View and manage team members and their roles",
		keywords: [
			"organization",
			"members",
			"team",
			"users",
			"roles",
			"people",
			"collaborators",
			"permissions",
			"access",
			"admin",
			"owner",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_MEMBERS_INVITE,
		section: "organization",
		title: "Invite Members",
		description: "Invite new members to your organization",
		keywords: [
			"organization",
			"members",
			"invite",
			"add",
			"new member",
			"team",
			"share",
			"collaborate",
			"email",
			"send invite",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_MEMBERS_PENDING_INVITATIONS,
		section: "organization",
		title: "Pending Invitations",
		description: "View and manage pending organization invitations",
		keywords: [
			"organization",
			"members",
			"invite",
			"invitation",
			"pending",
			"team",
			"waiting",
			"sent",
			"cancel",
			"resend",
			"email",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_THEME,
		section: "appearance",
		title: "Theme",
		description: "Choose your theme",
		keywords: [
			"appearance",
			"theme",
			"dark",
			"light",
			"dark mode",
			"light mode",
			"colors",
			"night",
			"system",
			"visual",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_MARKDOWN,
		section: "appearance",
		title: "Markdown Style",
		description: "Rendering style for markdown files",
		keywords: [
			"appearance",
			"markdown",
			"style",
			"tufte",
			"rendering",
			"preview",
			"format",
			"display",
			"md",
			"readme",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_CUSTOM_THEMES,
		section: "appearance",
		title: "Custom Themes",
		description: "Import custom theme files",
		keywords: [
			"appearance",
			"custom",
			"themes",
			"import",
			"json",
			"color scheme",
			"upload",
			"personalize",
			"customize",
		],
	},
	{
		id: SETTING_ITEM_ID.RINGTONES_NOTIFICATION,
		section: "ringtones",
		title: "Notification Sound",
		description: "Choose the notification sound for completed tasks",
		keywords: [
			"notifications",
			"notification",
			"sound",
			"ringtone",
			"audio",
			"alert",
			"bell",
			"tone",
			"complete",
			"done",
			"finished",
			"chime",
			"mute",
			"volume",
		],
	},
	{
		id: SETTING_ITEM_ID.KEYBOARD_SHORTCUTS,
		section: "keyboard",
		title: "Keyboard Shortcuts",
		description: "View and customize keyboard shortcuts",
		keywords: [
			"keyboard",
			"shortcuts",
			"hotkeys",
			"keys",
			"bindings",
			"keybindings",
			"commands",
			"ctrl",
			"cmd",
			"alt",
			"customize",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_CONFIRM_QUIT,
		section: "behavior",
		title: "Confirm before quitting",
		description: "Show a confirmation dialog when quitting the app",
		keywords: [
			"features",
			"confirm",
			"quit",
			"quitting",
			"exit",
			"close",
			"dialog",
			"warning",
			"prompt",
			"unsaved",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_BRANCH_PREFIX,
		section: "behavior",
		title: "Branch Prefix",
		description: "Default prefix for new branch names",
		keywords: [
			"features",
			"branch",
			"prefix",
			"naming",
			"git",
			"worktree",
			"author",
			"github",
			"username",
			"feat",
			"custom",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_PRESETS,
		section: "terminal",
		title: "Terminal Presets",
		description: "Manage your terminal presets",
		keywords: [
			"terminal",
			"preset",
			"presets",
			"commands",
			"agent",
			"launch",
			"default",
			"startup",
			"config",
			"shell",
			"run",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_QUICK_ADD,
		section: "terminal",
		title: "Quick Add Templates",
		description: "Pre-configured terminal presets",
		keywords: [
			"terminal",
			"quick",
			"add",
			"template",
			"claude",
			"codex",
			"gemini",
			"cursor",
			"opencode",
			"ai",
			"assistant",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_AUTO_APPLY_PRESET,
		section: "terminal",
		title: "Auto-apply Default Preset",
		description: "Automatically apply default preset when creating workspaces",
		keywords: [
			"terminal",
			"preset",
			"default",
			"auto",
			"apply",
			"workspace",
			"create",
			"new",
			"startup",
			"launch",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_PERSISTENCE,
		section: "terminal",
		title: "Terminal Persistence",
		description: "Keep terminal sessions running in background",
		keywords: [
			"terminal",
			"persistence",
			"background",
			"daemon",
			"session",
			"keep alive",
			"restore",
			"resume",
			"reconnect",
			"restart",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_SESSIONS,
		section: "terminal",
		title: "Active Sessions",
		description: "View and manage active terminal sessions",
		keywords: [
			"terminal",
			"sessions",
			"active",
			"running",
			"kill",
			"terminate",
			"process",
			"stop",
			"manage",
			"pty",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_LINK_BEHAVIOR,
		section: "terminal",
		title: "Link Behavior",
		description: "How to open links from terminal",
		keywords: [
			"terminal",
			"link",
			"click",
			"open",
			"external",
			"editor",
			"file",
			"url",
			"path",
			"cmd",
			"ctrl",
			"browser",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_LINEAR,
		section: "integrations",
		title: "Linear",
		description: "Sync issues bidirectionally with Linear",
		keywords: [
			"integrations",
			"linear",
			"issues",
			"tasks",
			"sync",
			"connect",
			"connected",
			"project management",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_GITHUB,
		section: "integrations",
		title: "GitHub",
		description: "Connect repos and sync pull requests",
		keywords: [
			"integrations",
			"github",
			"repos",
			"repositories",
			"pull requests",
			"pr",
			"sync",
			"connect",
			"connected",
			"version control",
			"git",
		],
	},
	{
		id: SETTING_ITEM_ID.BILLING_OVERVIEW,
		section: "billing",
		title: "Current plan",
		description: "View your current subscription and usage",
		keywords: [
			"billing",
			"plan",
			"subscription",
			"pro",
			"free",
			"enterprise",
			"current",
			"payment",
		],
	},
	{
		id: SETTING_ITEM_ID.BILLING_PLANS,
		section: "billing",
		title: "All plans",
		description: "Compare and upgrade plans",
		keywords: [
			"billing",
			"upgrade",
			"pricing",
			"plans",
			"pro",
			"enterprise",
			"compare",
			"features",
		],
	},
	{
		id: SETTING_ITEM_ID.BILLING_USAGE,
		section: "billing",
		title: "Usage limits",
		description: "Track workspace and user limits",
		keywords: [
			"billing",
			"usage",
			"limits",
			"workspaces",
			"users",
			"quota",
			"seats",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_NAME,
		section: "project",
		title: "Project Name",
		description: "The name of this project",
		keywords: ["project", "name", "rename", "title", "label"],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_PATH,
		section: "project",
		title: "Repository Path",
		description: "The file path to this project",
		keywords: [
			"project",
			"path",
			"repository",
			"folder",
			"directory",
			"location",
			"git",
			"repo",
			"root",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_SCRIPTS,
		section: "project",
		title: "Scripts",
		description: "Setup and teardown scripts for workspaces",
		keywords: [
			"project",
			"scripts",
			"setup",
			"teardown",
			"bash",
			"shell",
			"automation",
			"hooks",
			"init",
			"initialize",
			"cleanup",
			"onboarding",
			"config",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_BRANCH_PREFIX,
		section: "project",
		title: "Branch Prefix",
		description: "Override the default branch prefix for this project",
		keywords: [
			"project",
			"branch",
			"prefix",
			"naming",
			"git",
			"worktree",
			"author",
			"github",
			"username",
			"feat",
			"custom",
			"override",
		],
	},
	{
		id: SETTING_ITEM_ID.WORKSPACE_NAME,
		section: "workspace",
		title: "Workspace Name",
		description: "The name of this workspace",
		keywords: ["workspace", "name", "rename", "title", "label"],
	},
	{
		id: SETTING_ITEM_ID.WORKSPACE_BRANCH,
		section: "workspace",
		title: "Branch",
		description: "The git branch for this workspace",
		keywords: [
			"workspace",
			"branch",
			"git",
			"worktree",
			"checkout",
			"switch",
			"feature",
		],
	},
	{
		id: SETTING_ITEM_ID.WORKSPACE_PATH,
		section: "workspace",
		title: "File Path",
		description: "The file path to this workspace",
		keywords: ["workspace", "path", "folder", "directory", "location", "root"],
	},

	// API Keys
	{
		id: SETTING_ITEM_ID.API_KEYS_LIST,
		section: "apikeys",
		title: "API Keys",
		description: "Manage API keys for MCP server access",
		keywords: [
			"api",
			"key",
			"keys",
			"mcp",
			"claude",
			"integration",
			"external",
			"access",
			"token",
			"authentication",
		],
	},
	{
		id: SETTING_ITEM_ID.API_KEYS_GENERATE,
		section: "apikeys",
		title: "Generate API Key",
		description: "Create new API keys for external integrations",
		keywords: [
			"api",
			"key",
			"generate",
			"create",
			"new",
			"mcp",
			"claude desktop",
			"claude code",
		],
	},
];

export function searchSettings(query: string): SettingsItem[] {
	if (!query.trim()) return SETTINGS_ITEMS;

	const q = query.toLowerCase();
	return SETTINGS_ITEMS.filter(
		(item) =>
			item.title.toLowerCase().includes(q) ||
			item.description.toLowerCase().includes(q) ||
			item.keywords.some((kw) => kw.toLowerCase().includes(q)),
	);
}

export function getMatchCountBySection(
	query: string,
): Partial<Record<SettingsSection, number>> {
	const matches = searchSettings(query);
	const counts: Partial<Record<SettingsSection, number>> = {};

	for (const item of matches) {
		counts[item.section] = (counts[item.section] || 0) + 1;
	}

	return counts;
}

export function getMatchingItemsForSection(
	query: string,
	section: SettingsSection,
): SettingsItem[] {
	return searchSettings(query).filter((item) => item.section === section);
}

export function isItemVisible(
	itemId: SettingItemId,
	visibleItems: SettingItemId[] | null | undefined,
): boolean {
	return !visibleItems || visibleItems.includes(itemId);
}
